### ISSUE TITLE
Visibility of fields and functions in Abstract Country

### ISSUE THREAD

**Issue by azyzio** [farhanrahman/kyoto#10]
Our current implementation of Abstract Country defines all the fields as protected. What it means is that the agent can modify every parameter, e.g. country A may double their available cash every tick.
This would be considered cheating and we assume that no country would do it as it would destroy the game. This is however very unprofessional from the software engineering point of view.

Do you think we should stick to the way it is implemented now or
Change implementation so all the fields are private and we have protected getters to access the functions. This would require some work to modify most of the functions in AbstractCountry.

**Comment by tumblerer** [comment]
This is similar to what Darby(?) amongst others proposed.  It would also stop people accidentally changing their parameters.  I'd consider changing this to a task and assigning it.

**Comment by azyzio** [comment]
I will deal with it after finished what I am working on now.
If there is anyone thinking it is a bad idea, shout quickly

**Comment by cmd08** [comment]
Private fields and protected getters still wouldn't hide any information though, would it?

**Comment by Sergeus** [comment]
Private fields would mean that functionality implemented in inherited classes (Eg. everyone's country implementation) couldn't modify any of those data fields.   While certainly possible for some, it seems to make it unnecessarily complicated.   If we did make them private and use getters instead, none of the code in AbstractCountry would be affected, only that of inherited classes.   (I'm not even 100% sure inherited classes can READ private superclass fields.)

**Comment by cmd08** [comment]
A class cannot read the superclass's private fields, but it can access the
protected getters/setters.

I think we've basically uncovered a problem we can do little about:
inheritance is not the solution, we should probably have used interfaces
instead somehow.

On 11 June 2012 21:17, Stuart Holland <
reply@reply.github.com

**Comment by Sergeus** [comment]
I think inheritance is a decent solution, because we have a lot of shared code that otherwise would have to have been duplicated.   I'd say we keep them protected as they are though.   Just make sure no one writes a behavior that gives themselves free money.   That's not cheating the game, it's damaging the project.

**Comment by azyzio** [comment]
What is the problem of using getters in the inherited classes?

**Comment by azyzio** [comment]
Ok, I did some more research into how we can control access to members of the class (there is something quite interesting as  package-private fields) and I realized that this issue is not important enough to change all our classes at this stage.

I consider it breaking the rules of OO, but we should not be concerned with changing the whole implementation as the program is going to work just fine without this change.
