### ISSUE TITLE
Data: Bahamas unrealistic data

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#100]
Bahamas has a ridiculous level of energy output.  More than twice the output of Canada and almost as much as Russia.

**Comment by ncocacola** [comment]
I think I must have gotten confused with all this sorting & Excel columns etc.
All other values have been corrected (with a made up Fossil Fuel % as agreed).

The new kyotoCountryData.xlsx & kyotoCountryData.csv have been pushed to my repository.

Let me know if you spot any other mistakes.

**Comment by Sergeus** [comment]
This is clearly because the Bahamas is AWESOME.

**Comment by azyzio** [comment]
like
