### ISSUE TITLE
GDPRate calculation

### ISSUE THREAD

**Issue by piotroslaw** [farhanrahman/kyoto#101]
The function to update GDPRate in AbstractCOuntry was missing break statements in switch/case, I have just corrected it. As it was, it would always return RECESSION as eceonmy state.

Which leads to a question - was this tested? Are the formulas correct? I am asking because they are slightly different in the document on google docs, and frankly I have no idea how the formula works.

**Comment by tumblerer** [comment]
The formula is fine and was tested in isolation from the economy code.

**Comment by piotroslaw** [comment]
ok
