### ISSUE TITLE
Ticks, Years and updates

### ISSUE THREAD

**Issue by georgePil** [farhanrahman/kyoto#102]
To the creator of time and general consideration,

Why can't  the update of GDP, available to spend etc be done every tick instead of every year?

I think its more sensible since the game needs to be up to dated every instance, every tick not just every year.

Transactions are done every tick and many transactions take into consideration your current cash.

Non Annex One behaviour which is basically growth(increase in GDP) now happens every year which makes 365 ticks useless since it can not really do anything else during that time, just CDM.

**Comment by piotroslaw** [comment]
Even if you are right, it's too late to do a pretty drastic change like this. I have thought of it recently, and if we could do it all again, there would probably be many changes. But right now, I think the goal is to have a working simulation with independent agents, even if their strategies are not really perfect or diverse.
