### ISSUE TITLE
AbstractCountry Extraneous Reporting Functions

### ISSUE THREAD

**Issue by Sergeus** [farhanrahman/kyoto#103]
There are several methods in AbstractCountry which look like they're part of the carbon reporting service, but are very confusingly named and look like they can be deprecated.   They involve sharedState and all sorts of very strange things I don't quite understand enough to pull the functions out.   The functions are:

addtoReports()
getCarbonEmissionReports()
reportCarbonEmission()
getSharedState()

Can these all be removed?   If not, can they be renamed?

**Comment by piotroslaw** [comment]
Adding to this, the function reportCarbonOuput is called twice in execute() in AbstractCountry. I assume this is an error?

**Comment by Sergeus** [comment]
Turns out we need to use these.
