### ISSUE TITLE
Carbon Handler - Binary Search

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#105]
The binary search may well not do enough iterations to get an accurate answer.  The values of energyOuput are in the order x10^9.

Checkout it out and either mark it safe, or fix.

**Comment by n1kunj** [comment]
The previous number of iterations was 20. This results in a maximum error of about 953 parts in 10^9. I've increased the number of iterations to 30, which decreases the error to a little under 1 part in 10^9.
