### ISSUE TITLE
Storing information about emission target

### ISSUE THREAD

**Issue by azyzio** [farhanrahman/kyoto#11]
At the moment the emission targets are stored in two places: in shared state handled by CarbonTarget and in each country as a field.

If we decide that our solution is service based, we should get rid of the emissionTarget field in Abstract Country and query the shared state whenever we need to access this information.

Is my thinking correct here?

**Comment by tumblerer** [comment]
I think that's broadly correct.  I'd like to to check with Jonny with regards to when he updates the shared space. 

Further to that I like the current neatness in controlling when fields are updated when from within Countries in the execute function.  This could prevent some difficult timing issues later on.

**Comment by webbo89** [comment]
I hope this still works with you - Current plan is at simulation start time we'll be pulling in a table of country data. Whatever you decide on, we can either have target set in the shared state or in the country agent constructor.

**Comment by azyzio** [comment]
I think emission target is not defined from 1990 data, but we are calculating it with the service created by Jonny, so I don't think that there will be a need to pull it from a db.

**Comment by cmd08** [comment]
Each country has to keep a track of its own emissions target. Admittedly, this needn't be in AbstractCountry, but still if I were writing the implementation for a participant, I would want to keep a local value stored.

**Comment by tumblerer** [comment]
I'd agree with Chris, countries should keep track of their own emissionTargets which are pulled from the sharedspace at specific times.

Adam's right, emission targets aren't listed in the database, their calculated at the beginning of the game.

**Comment by tumblerer** [comment]
I think we'll leave this as it is for the moment.
