### ISSUE TITLE
Move Repository to organisation

### ISSUE THREAD

**Issue by farhanrahman** [farhanrahman/kyoto#12]
So I just discovered that if we made an organisational repository it would have been much better. I didn't know about this thing until today. Basically its much neater than having it on someone else's account, because having it on an organisation gives us more admin management facilities, looks cooler!!

I can transfer the repository but the issue is I don't know what could happen if I do. Things can get messed up!! I emailed github about this issue and I hope they get back to me.

However once our development commits become a bit infrequent and we are at a good position I suggest that we move to the new repository in the organisation. I created the organisation: 

www.github.com/kyotoprotocol

let me know what you guys think!

**Comment by azyzio** [comment]
If anything including the push history (as seen in Network tab), posts (seen in Issues tab) is going to be lost, then I am against the change.
Otherwise, it is really up to you. Personally, I wouldn't waste time if it has no impact on our work.

**Comment by webbo89** [comment]
I'm up for it. We've got to put our apache web UI somewhere, and khadivi has a repo for data - could fit nicely under one roof.

**Comment by webbo89** [comment]
PS @azyzio  - history won't be lost, its simply an ownership change!

**Comment by Sergeus** [comment]
What do we gain from this?   I'm a bit concerned that we seem to be potentially altering the project for no reason.   I understand that organizations offer some benefits, but none of them seem particularly applicable to our setup, unless I've missed some.

**Comment by webbo89** [comment]
We could instead transfer the project once we've completed it.

**Comment by azyzio** [comment]
@farhanrahman Do you want to carry on with the change? If so I guess it's better to do it today when no one has any uncommitted changes on their machines.

**Comment by farhanrahman** [comment]
I think we should first discuss about this in tomorrow's meeting and see what everyone has to say. Once changed i will fire off an email with intructions to change the remote repository....
