### ISSUE TITLE
Class kyoto/services/Economy#updateEconomyState uses a new Random in each invocation

### ISSUE THREAD

**Issue by gubby** [farhanrahman/kyoto#120]
A new Random instance is seeded based on the System.nanoTime which means the sequence will be predictable.

**Comment by piotroslaw** [comment]
This seems like the last thing we should be worrying about right now to be honest.

If I misunderstood and this is really a game-breaking problem please reopen this, but closing for now

**Comment by gubby** [comment]
Its a broken feature and a 2 second fix. Its your project, I'm not
re-opening anything! You're welcome anyway.

On 22 June 2012 15:01, Piotr Dittrich <
reply@reply.github.com
