### ISSUE TITLE
NullPointerException: For NonAnnexOne Sims

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#121]
Running a sim with only nonAnnexOne countries causes a null pointer exception upon checking the monitor.

**Comment by georgePil** [comment]
Should be fixed now

**Comment by georgePil** [comment]
setKyotoMemberLevel(KyotoMember.NONANNEXONE) moved in constructor

**Comment by jjonnnyy** [comment]
Yup, fixed in commit: 4dfdd65c7be008617abdcd33247fedd143049f2f.
