### ISSUE TITLE
TradeProtocol is unpredictable

### ISSUE THREAD

**Issue by piotroslaw** [farhanrahman/kyoto#122]
A test case:

Agent A sends offers every tick.
Agent B agrees to all offers it receives.

What happened:

B received first two offers (from ticks 3 and 4) in tick 5, and offer from tick 5 in tick 6. In the end, the trade proposed in tick 3 was finalised in 9 (as in, that's when agents got the confirmation message).

Seems that the timing of offers is completely random.

This might not be game-breaking, but is something to be aware of for behaviour writers.

**Comment by farhanrahman** [comment]
yeah...i am not too sure how the messaging of the Presage framework works. I'll email Sam to find whats going on here.
