### ISSUE TITLE
Canada agent has copied code from non annex one

### ISSUE THREAD

**Issue by farhanrahman** [farhanrahman/kyoto#127]
I was going through the code of canada agent and i can see that code has been copied from NonAnnexOne.

The function that was copied from NonAnnexOne is the following:

``` java
private void energy_increase_with_care(double money_invest) throws IllegalArgumentException, Exception{
....
}
```

The reason why I am saying this is because you are not supposed to have the same implementation as another country. The whole point of this was so that agents can have their own unique behaviour. @Raamaa please fix this.

**Comment by Raamaa** [comment]
I was merely using it as a reference and have not actually used it to implement anything in my code. Sorry about it. HAve removed it.
