### ISSUE TITLE
Kyoto UI breaking Presage CLI

### ISSUE THREAD

**Issue by webbo89** [farhanrahman/kyoto#129]
Can anyone let me know a simID / name that broke the presage CLI list cmd ?

IT's most likely a type definition that we've missed or got wrong!

I suspect it is field: finishTime, we're saving as a longINT (mongo INT 64) but the presage CLI saves them as Int31 ...

**Comment by webbo89** [comment]
Which sim causes this: Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long

**Comment by farhanrahman** [comment]
72

**Comment by webbo89** [comment]
Did you try resaving? Ideally users wopuldnt change the I'd of the sim... So delete sim 72 to save the trouble!
------Original Message------

**Comment by webbo89** [comment]
OK presage CLI now working again.

Changing sim ID is not allowed!
