### ISSUE TITLE
Emission Target and Carbon Offset adjusted every year?

### ISSUE THREAD

**Issue by piotroslaw** [farhanrahman/kyoto#13]
I have read through "Carbon Offset - A Meaning Of", and have two questions:
- According to the model, the carbon offset that we buy only lasts till the end of the year. Say, a country has a carbon output of 110, and its target is 100. Then, if it doesn't invest in reduction/absorption etc, it has to buy 10 credits from other countries every year in order not to face sanctions. Shouldn't credits last for entire session, instead of being "cancelled" every year?
- As far as I know, it was decided that each of the countries' session target would be divided into smaller year targets. Could someone explain why? Shouldn't it depend on the country when they want to limit their emissions/buy credits etc? This way, there would be much more room for strategy of when reduction/absorption/buying/investing is most profitable. As it is in the document now, an idea of "session" becomes meaningles, since the targets and offsets are set again every year anyway.

**Comment by georgePil** [comment]
Credits should be maintained through the whole session and not cancelled since countries might want to have a long term economic strategy!

**Comment by tumblerer** [comment]
Credits do in effect last the entire the session.  However, they get used up year on year to account for their lack of carbonReduction.  This is because new emissionTargets are given to the agents every year.

The reason for year on year targets is to take into account how GDPRate is calculated. Think of the situation where someone could pump their GDP rate at the expense of carbonOutput for 9 years in a row.  They reap that benefit and just before their carbonOutput gets checked, they scale down their industry and don't get sanctioned.

Sessions do have meaning, since the emissionTargets for the next 10 years are recalculated taking into account global carbonOutput.

It would be easiest to explain this face to face.

**Comment by azyzio** [comment]
Both of your questions are actually touching the same issue - what carbon offset really is.

I will first address the first question. Targets are set on yearly basis as our measures of Carbon Output and Energy Output are on yearly basis. I.e. they define how much carbon you are using in one year. Investing in carbon reduction decreases your yearly production so this measure seems very reasonable.
The reasons we are not defining carbon output per session:
- There would be a problem getting such data
- The GDP changes every year and so should carbon output which is closely related to GDP.

Therefore emission targets are also set in the same unit - i.e. carbon emission per year. Also, the monitoring is operating on yearly basis and there needs to be a way to check if the country is making progress. I know it is limiting in a way, but there was no better way which would satisfy all the needs.

Answering your first question: I thought I have described it quite well in "Carbon Offset - A meaning of", but I will try again here. Using your example: country is using 110 per year and its target is 100 per year. It has therefore bought 10 (not per year) which it can use in any year in the session. As it would be sanctioned, it is using it in the first year, so it doesn't have access to this 10 in the following year. They are not getting cancelled, they are being used.

Regarding the question about the utility of sessions. On session basis the carbon offset will be reset (here the carbon that was actually not used will be lost). Also, the world total carbon emission will change and the target setting will follow different algorithm.

**Comment by piotroslaw** [comment]
Ah, makes sense. Seems I misunderstood the wiki. Thanks for explanations.
