### ISSUE TITLE
Simulations on server GDPs are 6 orders of magnitude incorrect

### ISSUE THREAD

**Issue by n1kunj** [farhanrahman/kyoto#131]
On the server, the GDPs for the mini simulation is in millions of dollars. We need them in dollars.

I'm off to stab myself in the face, because it took me three hours to figure this out.

**Comment by tumblerer** [comment]
This is probably a case of the csv data being incorrect. I'll look into it tomorrow, but I thought I corrected it.

**Comment by tumblerer** [comment]
Fixed it.  Hopefully the website will be repulled from the git in the near future

**Comment by webbo89** [comment]
Does this require any action on the UI part? defaultdata appears to match Khadivis.

Also the git server is pulled every half hour.

**Comment by tumblerer** [comment]
No, its just mini simulation hadnt been updated, but it done now.
