### ISSUE TITLE
Cyprus keeps failing at investing in arable land

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#133]
Cyprus repeatedly tries to invest in absorption when it doesn't have enough land

**Comment by georgePil** [comment]
I will be there in half an hour and fix this

**Comment by ncocacola** [comment]
Ask Pilikos, maybe he can talk some sense into his fellow Cypriot
countrymen.

On 24 June 2012 14:03, Chris <
reply@reply.github.com
