### ISSUE TITLE
"Factories" and effect on economy(availabletoSpend variable)

### ISSUE THREAD

**Issue by georgePil** [farhanrahman/kyoto#14]
In order for countries to be able to increase their energy output and thus their economic growth, countries should be able to "build" factories and thus those factories have an effect on the energy output.. Do you think we should have a general constant value for that effect or just let countries decide? Also what would the cost be for those "factories", because countries should not be able to spend unlimited number of money on increasing energyoutput since energyoutput is used for calculating GDPrate ?

**Comment by tumblerer** [comment]
This has already been considered and implemented in EnergyUsageHandler.

The cost of upgrading is constant across countries, although this could be changed (for example, to be a percentage of GDP).  However, i think this will be left as is for the moment.

You can increase energyOutput all you want, but your carbonOutput will also increase, meaning you'll find it harder to meet emissionTargets.  See the Country Action file in google docs for more info.

**Comment by georgePil** [comment]
In the EnergyUsageHandler you just set an "investment value" which then becomes carbon essentially since carbon investment price is 1. ie money -> carbon money->energy..which makes sense but is not entirely what happens in reality. Different "currencies" could be used but this can be done inside the countries depending on the cost of investing in energyOutput

**Comment by tumblerer** [comment]
The actual value of constants are currently quite arbitrary, and have not be tested or fine tuned.  Much of what happens in the game probably falls into the category, "makes sense but is not really realistic".

The countries need a common method for costing investment.  Not saying the cost has to be the same, but the way of deriving it must be.   The idea of currencies was rejected a while ago.
