### ISSUE TITLE
Monitoring Costs Strategy

### ISSUE THREAD

**Issue by azyzio** [farhanrahman/kyoto#2]
I can see that a lot of development was done on Monitoring service, but it is now using the strategy of randomly choosing the country to monitor and charging it for it. Why exactly are we using this strategy?

There were 3 strategies that we have considered:
1. Taxing the transaction. We decided not to use it as transactions are done between the countries and no body is actually controlling them, so there should be no body that implements taxation
2. Monitoring can always happen. Monitoring service can basically monitor every time it wants. This was a bad idea because it is really unreal and makes cheating really impossible.
3.Each country pays the service each year a constant amount of money. Monitoring service can use it to monitor any country that they choose based on some algorithm (e.g. countries that cheated most in the past will be monitored more frequently). This was the strategy that we have decided is most realistic and fair.

Why are we then charging the country that we monitor? In this case we can basically monitor every country in every round and they will have pay for it. Doesn't seem either fair nor real (as countries would never accept such conditions and wouldn't join kyoto)

**Comment by tumblerer** [comment]
Those are pretty valid points. 

I'd like to put together another list of issues that we can spend tomorrow discussing, preferably face to face. 

For the moment I'd leave them as is.

**Comment by azyzio** [comment]
Solution:
Each country pays a monitoring tax every year. The cash that the monitoring service gets through taxation is spent on monitoring random countries.
