### ISSUE TITLE
Carbon absorption just grants you offset once

### ISSUE THREAD

**Issue by piotroslaw** [farhanrahman/kyoto#20]
What happens now is, when you plant trees, you get a single reward in carbon offset.

This is slightly illogical - trees absorb carbon all the time, not just once. Conceptually, the ideal situation would be to grant carbon offset every year, for each tree block planted since the start of simulation. However, this would be difficult to implement - we don't store the amount of planted trees anywhere.

Another solution would be to reduce carbon output every time you plan trees. The problem is, this influences your dirty industry (carbonOutput / energyOutput), which in itself influences the price of carbon reduction. So, after plantng trees, it would be more expensive to clean your industry, which doesn't make sense.

Hence, the only viable solution that has been proposed is to introduce another variable: carbonAbsorption. Every time you plant trees, it is increased by some amount, measured in CO2 per year. So in effect, the condition you have to satisfy every year becomes:

carbonOutput - carbonAbsorption - carbonOffset <= emissionTarget

I have started to implement it, and will merge with development soon. This means, every country has to modify their constructor slightly (just add another variable).

If anyone has any issues, comments etc, write here. If everyone's ok with that, I will close this issue in the evening.

**Comment by piotroslaw** [comment]
Just realised countries do not even have to change anything - the variable will be initialised to 0, hence no need to alter the contructor.

**Comment by Sergeus** [comment]
Can this issue be closed then?   Your solution seems to work well.

**Comment by piotroslaw** [comment]
done.

**Comment by tumblerer** [comment]
Excellent.  Push it to dev and done.

**Comment by piotroslaw** [comment]
already on dev
