### ISSUE TITLE
JUnitTests branch and folder structure

### ISSUE THREAD

**Issue by ncocacola** [farhanrahman/kyoto#21]
Hey guys,

Please make sure that anything you do in /src/main/test is done on the JUnitTests branch. 
During "work days", development is merged into it every hour or so (to get the most up-to-date code to test) and JUnitTests is merged into development at the end of each day (this is done mainly to avoid "polluting" development with test commits during the day - if you think there's a better strategy to be used, please suggest it). 

Also, Darby, it seems you've broken the folder structure ("java.uk.ac.ic.kyoto.trade" instead of "uk.ac.ic.kyoto.trade") :P

Any questions about the branch, feel free to ask :)

Cheers!

Bananaman

**Comment by cmd08** [comment]
The folder structure? Or package names? And in which commit was this broken?
