### ISSUE TITLE
Add agent implementing carbon absorption/reduction to basic simulation

### ISSUE THREAD

**Issue by oliviervg1** [farhanrahman/kyoto#22]

**Comment by piotroslaw** [comment]
Update on the task: Chris is doing CarbonReductionHandler testing, I am doing CarbonAbsorptionHandler testing. For now, neither handler works properly.

**Comment by piotroslaw** [comment]
Core part works, Nik will just do some testing on one of the additional utility function (which is not crucial - explained in google docs document)

**Comment by piotroslaw** [comment]
which pretty much means this task should be closed
