### ISSUE TITLE
AbstractCountry.java currently monitors all countries including rogue states.

### ISSUE THREAD

**Issue by oliviervg1** [farhanrahman/kyoto#23]
Tom is trying to fix this.

**Comment by tmclayson** [comment]
Basic classes written, awaiting MongoDB access agent from farhan for final implementation.

**Comment by Sergeus** [comment]
Why do we need mongoDB access to implement not monitoring rogue states?   Can't we create a boolean field in AbstractCountry that's something like "isKyotoMember"?

**Comment by tmclayson** [comment]
That would probably be easier...guess I got caught up in the moment a bit
and jumped on the first suggestion that seemed reasonable.

On 12 June 2012 12:49, Stuart Holland <
reply@reply.github.com

> wrote:
> 
> Why do we need mongoDB access to implement not monitoring rogue states?
> Can't we create a boolean field in AbstractCountry that's something like
> "isKyotoMember"?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/farhanrahman/kyoto/issues/23#issuecomment-6268377

## 

Tom Clayson
Information Systems Engineering - ISE3 (MEng)
Imperial College London
Department of Electrical & Electronic Engineering
TEL(UK) : +447774014054
TEL(ES):  +34692705912

**Comment by azyzio** [comment]
So how is it currently working?

**Comment by Sergeus** [comment]
I'm working on this right now, just making some small changes to AbstractCountry.   But I gather there are some certain Kyoto members who don't pay monitor tax or something?   Who are they so I can exclude them in a reliable manner?

**Comment by azyzio** [comment]
If such members exist then they don't have to be specified by name but there should be a boolean parameter PaysTax than marks them.

**Comment by azyzio** [comment]
But why would a country not pay taxes if it is in kyoto? :D

**Comment by Sergeus** [comment]
It has thus been decreed that for all countries, regardless of annex, carbon output, or offset, monitor tax shall be paid forthwith on the first turn of every new year, from now until the end of simTime.
