### ISSUE TITLE
Extend Trade Protocol to Implement Clean Development Mechanism

### ISSUE THREAD

**Issue by Sergeus** [farhanrahman/kyoto#28]
Using Trade Protocol or otherwise, we should be able to implement the clean development mechanism.   (Annex 1 countries investing in non-annex1 countries, providing the monetary benefit for the 'investee' and generating carbon credits for the investor.   Note: This is not the same as a purchasing transaction.)

**Comment by sc1109** [comment]
Challenge accepted!

**Comment by sc1109** [comment]
CDM is so similar to a normal trade, the only difference I can see is the initiator (investee) doesn't lose credits.

So I propose we use TradeProtocol with a new enum added to TradeType called CDM so that TradeProtocol can detect whether or not to deduct credits from the investee.

Problem?

**Comment by sc1109** [comment]
Hey @farhanrahman ! adjust TradeProtocol to account for the new generic Offer!

**Comment by sc1109** [comment]
Farhan is there really any point to Offer being generic? It feels like the most natural way to add CDM is by adding INVEST and RECEIVE to the TradeType enum.

**Comment by sc1109** [comment]
@farhanrahman : So I've added CDM by extending the TradeType enum and will try to test now
