### ISSUE TITLE
Actions to Perform by Agents

### ISSUE THREAD

**Issue by georgePil** [farhanrahman/kyoto#29]
According to the document How Time Works ( A Brief history thereof) agents need to be added to the monitoring service, connect to reporting service and query for emission targets initially. 

Addressing to the author :p or anyone who might know, it is my belief that Non-Annex 1 countries do not require to do this.

Also since Non Annex 1 countries are not being monitored then do not require to -Pay  monitor tax  or submit any reports for monitoring. 

Correct me if I m wrong

Cheers!

**Comment by farhanrahman** [comment]
So currently the countries will be monitored only if they are not non-annex1 but that feature hasn't been added yet. Tom was working on something to get that done but it wasn't done by today...

**Comment by tumblerer** [comment]
You're right.
