### ISSUE TITLE
Carbon Reduction Handler Values

### ISSUE THREAD

**Issue by Sergeus** [farhanrahman/kyoto#31]
Currently, the carbon reduction handler works in a flow of control perspective, but the values it returns for given investments are way out of range.   (A marginal investment (10% of availableToSpend) when carbonOutput is 30,000 tons results in an output change in excess of 900,000)

**Comment by azyzio** [comment]
I don't understand the issue? Do you want to me to adjust the constants already?

**Comment by Sergeus** [comment]
I don't really follow the math within the carbon reduction handler, so I'm not sure if the errors derive just from the GameConst stuff or the internal math of the handler.   If it's possible to get it to output reasonable values for testing that would be awesome.

**Comment by azyzio** [comment]
OK, I will come up with some numbers.

**Comment by azyzio** [comment]
Ok, I have changed them so reasonable results should be found. Close the issue if it solved the problem.

**Comment by tumblerer** [comment]
Not solved. carbonOutputChange in CarbonReductionHandler.invest() is throwing huge negative numbers.

**Comment by tumblerer** [comment]
Ok, found the problem:

CarbonOutput in calculateCarbonOutput is calculated as energyOut *(1-cleanIndustry).  However clean industry is not always a positive number less than 1.

Hence the roots of your quadratic need to be smaller.

**Comment by piotroslaw** [comment]
Is it not? assuming carbonOutput < energyOuput, dirtyIndustry is their ratio (0 <= dirtyIndustry <= 1), so should work.

But I think there is an easier and more easy to work with way to calculate all of it, without using quadratic equations. Will propose something later.

**Comment by azyzio** [comment]
Clean industry is always supposed to be positive number between 0 and 1. I guess the values of EnergyOutput and CarbonOutput in the simulation are not correct.

**Comment by Sergeus** [comment]
The energyOutput and carbonOutput are initialized to correct values, but once the reduction handler supplies a massive change in one direction or the other, it breaks the formula for the second run at reduction.

**Comment by tumblerer** [comment]
@azyzio and @piotroslaw could you work something out between you?  

The values of energyOutput and carbonOutput are correct.  Frankly, there's no way they can be incorrect, since they could take any value aslong as energyOutput>=carbonOut

**Comment by azyzio** [comment]
As the Carbon Reduction is now using a slightly modified model, this issue is no longer valid.
