### ISSUE TITLE
Remove GDPRate, emissionsTarget from constructor.

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#32]
These can be removed from the constructor as they're calculated in game.

**Comment by azyzio** [comment]
emissionsTarget- yes
GDPRate - no

GDP Rate is recalculated every year based on the previous year value. We need an initial value to be able to calculate the next ones.
GDP Rate in 1990 is also a real data and we should use it to make the simulation as close to reality as possible.

**Comment by tumblerer** [comment]
You're right, forgot that it used previous data.  

As an aside, it's 1998 GDP rate that is used.

**Comment by tumblerer** [comment]
Done.  People need to fix up there constructors again. So sorry.
