### ISSUE TITLE
CarbonAbsorptionHandler model

### ISSUE THREAD

**Issue by piotroslaw** [farhanrahman/kyoto#33]
Basically, the issue in the handler is that the price of planting trees only depends on the arable area left for a country. But this is not realistic - imagine a situation:
- Country A has 1000 area, and 50 arable area.
- Country B has 60 area, and 50 arable area.

Cost of planting trees in both is the same now. However, it shouldn't be the case - Country A is heavily "crowded", so that little area left should be much more precious than for country B (much smaller country), of which most area is unoccupied.

My proposition is to base the price on the percentage of area left (arableArea / landArea) instead. This is analogous to CarbonReductionhandler model, where the price of reducing carbon depends on the cleanIndustry factor. This would mean we could use similar formula.

I would be happy to modify CarbonAbsorptionHandler when CarbonReductionHandler is working.

**Comment by azyzio** [comment]
This makes CarbonAbsorbtionHandler very similar in CarbonReductionHandler.

I have however discovered another problem with it.
Imagine a very unrealistic (but theoretically correct) situation:

Country A has area 100 and 100% of it is arable
Country B has area 100000 and 100% of it is arable

Now country A can invest in carbon absorption and changes 1% of its arable land into forest. It cost it, let's say $1000. It gives them 1*X in tonnes of carbon per year added to Carbon Absorption. (X is how much carbon per year is absorbed by 1 nit of forest)

Country B invests in carbon absorption and changes its 1% arable land into forest. It costs exactly the same - $1000 as the price depends on the percentage change. It however gives them 1000*X in tonnes of carbon per year in Carbon Absorption.

I think it is not very real, but acceptable for our model. What do you think?

**Comment by azyzio** [comment]
Same issue applies to carbon reduction.

**Comment by piotroslaw** [comment]
That's not what I meant.

My idea is that only price of a single block of forest depends on the percentage of area that is free (arable / total). Hence, using your example, planting trees on 1% of the area would cost different amounts. While the average price for a single block in the transaction (which we can calculate and use easily if it is a linear function) would be the same for both countries, Country B would have to pay for 1000 times more blocks than country A. Which is sensible, as it would get 1000 times higher absorption boost.

**Comment by piotroslaw** [comment]
Also, to comment on the function of cost itself: While quadratic is much more realistic, we think that it massively complicates things. Since we have very little time, it seems a better solution to use linear function so that it can work asap, and then, if we have time, do a quadratic function instead.

I think the formula will be realtively simple, I can implement it tomorrow at uni and write a wiki on it. It can be used both in reduction and absorption handlers.

So by the end of tomorrow, I think I'll manage to make the handlers working and hopefuly test them to prove so.

**Comment by piotroslaw** [comment]
Ok, I have heavily modified the CarbonReductionHandler, including its constants. Will do the same with AbsorptionHandler tomorrow, and will merge group2 which I am working in with dev.

Hence, be prepared that both will seriously change tomorrow early-afternoon, but it should not make much difference for anyone using the handlers, the only difference being that the functions now take doubles instead of longs.

**Comment by azyzio** [comment]
I have discussed the changes with Piotr and I have realized where my last model failed. Piotr's solution, although less mathematically "cool" fixes it, so I totally support what he is doing here.

**Comment by piotroslaw** [comment]
Done, closing.
