### ISSUE TITLE
Energy Usage Handler - reduceEnergyOutput()

### ISSUE THREAD

**Issue by georgePil** [farhanrahman/kyoto#34]
In the Energy Usage Handler, when a reduction in energy output is required/occurs this is probably removal of factories since they pollute ( carbon output) but also produce energy (energy output). Should there be an increase in the arablelandarea since factories are removed?

**Comment by n1kunj** [comment]
As investing in carbon industries doesn't consume arable land area, removal of factories shouldn't return it.

Whether we change it such that investing in carbon industries does consume arable land area is, however, a good question.

**Comment by azyzio** [comment]
I was thinking about it. Theoretically factories could take up some land. At the moment they do not.
When you build factories, arable land doesn't decrease. When you destroy them, it doesn't increase.
I think it is quite a reasonable model as factories take much less land than forests that have to be planted, so the area they take is neglectable.

Close the issue if you agree with me

**Comment by tumblerer** [comment]
We'll assume for the moment that you're building factories on non-arable Land. 

I think consuming Arable Land by building factories doesnt add very much to game, other than an aspect of realism and further complication to balancing the game.  It means more variables interact with each in other in obscure ways.

**Comment by georgePil** [comment]
Arable land area is the available area of a country so "factories" normally take space, since trees and factories are what control and change the carbon output, I though that both should change the arable land area since it is important in calculating costs( carbonAbsorption etc). 

Also since there are not many game strategies, if we go through with "factories" we could have different sorts of factories that change the carbonoutput , energyoutput differently, which is the case in real life (nuclear factories). I am happy to change it if people agree. If not I dont mind either :p just a suggestion

**Comment by georgePil** [comment]
Also factories take some space :p I dont know what forests your countries have but back home forests are as big as factories haha :p

**Comment by tumblerer** [comment]
Haha.  But no, I can't see this happening until we have a game that simulates and runs with all the functions that are needed.

It comes down to the difficulty of balancing the game as it becomes more complicated.

**Comment by Sergeus** [comment]
I think this is an unnecessary level of complexity.   Generally, forests, on a level that will affect carbon dioxide emissions, will be much larger than a factory which would create enough emissions to counteract that offset.   A large number of factories, in the real world, will be built on non-arable land.   It seems a suitable abstraction for our purposes, to assume factories are built on non-arable land.

**Comment by georgePil** [comment]
Ok fair enough, if there is time we reconsider!
