### ISSUE TITLE
Data for Africa

### ISSUE THREAD

**Issue by ncocacola** [farhanrahman/kyoto#35]
Hey guys (more specifically Adam and Webbo),

With regards to the data.csv file which will contain all the input data for the program, I have come across an issue that needs to be solved.

We agreed with Stuart and Tory, that countries where some data is missing would be removed from the data set (typically small islands that don't really matter). For the specific case of former Soviet Union countries, where a lot of 1990 data is missing, we agreed we'd input 1992 data instead.

The issue now is about a bunch of countries (mostly African - 53 countries in total), where we don't have the Fossil fuel % (i.e. we have carbon emissions data, so we know they use fossil fuels, but we don't know what percentage of their total energy consumption is from fossil fuels/carbon emissions).

The Fossil Fuels % will not be inputted into the program, but it is used to calculate the energyOutput field (i.e. if all the energy consumption of the country was fossil-based, how much carbon would it use)
using the formula energyOutput = carbonEmissions/FossilFuels.

Since we do not have the Fossil Fuels % for these 53 countries, we can't get energyOutput and thus do not have a full data set.

Three possible solutions to this problem:
- Remove these countries from the data set (we'll still have 120 countries to work with, but Africa will be poorly represented).
- Make up Fossil Fuels % and thus Energy Outputs for these countries.
- Get rid of energyOutput and find another way of doing what Adam does with it.

It'd be awesome if you could give me some input on what you think about this issue.

List of countries with this problem:
Antigua and Barbuda, Bahamas, Barbados, Belize, Bhutan, Burkina Faso, Burundi, Cambodia, Cape Verde, Central African Republic, Chad, Comoros, Djibouti, Dominica, Equatorial Guinea, Eritrea, Fiji, Gambia, Grenada, Guinea, Guinea-Bissau, Guyana, Kiribati, Laos, Liberia, Madagascar, Malawi, Maldives, Mali, Marshall Islands, Mauritania, Mauritius, Namibia, Niger, Palau, Papua New Guinea, Rwanda, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines, Samoa, Sao Tome and Principe, Seychelles, Sierra Leone, Solomon Islands, Somalia, Suriname, Swaziland, Tonga, Tuvalu, Uganda, Vanuatu

**Comment by tumblerer** [comment]
I dont think removing energyOutput is an option.

**Comment by azyzio** [comment]
Removing energy output is definitely impossible. Any alternative would meet the same problem.

I guess we can assume that those countries are 100% fossil fuelled. I guess they are generally >90% fossil fuelled anyway, so their strategy for the game would not be altered by making this assumption.

**Comment by tumblerer** [comment]
Good call.  I think that makes sense, as African states would have a lot of room for investment.

**Comment by ncocacola** [comment]
OK, what I'm going to do in this case is assign a 90+ percentage to these countries.
I'll use something like = 90% + a random percentage between 0 and 10 so that we don't have exactly the same percentage for each country?

Is that good with everyone?

**Comment by tumblerer** [comment]
Fine.
