### ISSUE TITLE
CarbonAbsorptionHandler getBlockCost() very broken. Also, number representations.

### ISSUE THREAD

**Issue by n1kunj** [farhanrahman/kyoto#36]
It always returns 0 because it uses longs instead of doubles, meaning carbon reduction is pretty much free for me in my test case. It's a bit late today but at some point we all need to sit down and properly figure out what number format we should be using for all variables. If we keep using longs for everything, we're going to have a bad time.

I suggest doubles and millions of dollars for everything, otherwise we're losing so much information, especially as a lot of stuff seems to be calculated using loops (rounding error after rounding error = problems).

**Comment by sc1109** [comment]
doubles for everything has already been agreed, I'll adjust CAH now

**Comment by tumblerer** [comment]
CarbonAbsorption is being adjusted/rewritten, as @piotroslaw has found some issues also.

See #33

**Comment by sc1109** [comment]
I mean I'm changing stuff to doubles, a change to measuring in millions is a different issue
