### ISSUE TITLE
CarbonAbsorptionHandler/AbstractPostCommunistCountry require updates for long->double conversion

### ISSUE THREAD

**Issue by sc1109** [farhanrahman/kyoto#37]
There is now some very dangerous looking methods which generate no warnings in both these files due to my meddling with the types in Abstract Country (all longs now doubles), please could the respective owners of these classes spend some time checking everything works?

**Comment by georgePil** [comment]
By changing the variables from long to doubles, changes in EnergyUsageHandler have to be done as well, for the calculateCostOfInvestingInCarbonIndustry(long carbon).

**Comment by azyzio** [comment]
Piotr is dealing with Carbon Absorption handling now. I am starting to work on Energy Usage Handler.

**Comment by azyzio** [comment]
The issue is resolved.
