### ISSUE TITLE
Timing of Annual functions

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#38]
We need check that each of the functions called at the end of years and sessions are called in the right order and at the right time.  

For example monitors issues need to be performed before emissionTargets are updated.

Further to that, the list of functions to call should be filled and finalised as much as possible

**Comment by azyzio** [comment]
re checkTargets() - it is deprecated and can be easily removed. Monitor does the target checking automatically.

**Comment by Sergeus** [comment]
For now, they seem to be ordered in a fairly sensible manner, and I fixed a hilarious timing bug with end of session calculations.   (End of session every turn for the first year ftw)   I need to make sure that the order used is consistent for targets and monitoring and stuff.
