### ISSUE TITLE
Change to AbstractCountry to assist TradeProtocol

### ISSUE THREAD

**Issue by farhanrahman** [farhanrahman/kyoto#39]
So today we came to a problem that after finishing the trade protocol functions should be called for every country to change the carbon offset and change the cash. These functions are implemented in the super class i.e. AbstracCountry but the problem with this is that every country can choose not to call this function and when the initialise their trade protocol. This means countries can do whatever they want in these functions which breaks the game.

So what I suggest is the following:

1) Initialise trade protocol in AbstractCountry: This gives the added advantage that all countries can have access to this tradeProtocol. If they wish to not use this then they can remove the canHandle() method in the processInput function.

2) Override the tradeProtocol carbon and cash changing functions with the ones that Stuart wrote today

3) Create an abstract function acceptExchange which is overriden in the sub classes which will have the country's own shizzle...

**Comment by tumblerer** [comment]
Implementing in AbstractCountry is the best.  The bool 

``` java
isKyotoMember = true
```

can be used to decide whether countries all allowed to take part.

**Comment by azyzio** [comment]
Why not:
Pass the reference to the abstract country as a parameter to trade protocol and then call those functions inside the protocol itself?
It would be proper encapsulation as it the exact moment of confirming the trade when the money and carbon offset should be updated.

**Comment by azyzio** [comment]
@farhanrahman can you update on the issue? From Tory's post in #40 I guess that you have decided to implement my solution. Is it introducing any problems?

**Comment by Sergeus** [comment]
We've moved tradeProtocol into the countries package and made the relevant variables package protected, so that trade protocol can operate on them.   We're doing testing on the alterations to trade protocol now.   Once these tests are finished, trade protocol should work fully and completely to do carbon trading like we want to, and then we can work on CDM stuff.

**Comment by farhanrahman** [comment]
I think this was quite a good fix, moving TradeProtocol to countries package and using package protection!! Or else you can have countries hack the TradeProtocol and generate extra cash!!! I am quite happy with the work today :)
