### ISSUE TITLE
Package Protected Variables

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#40]
We're thinking of making (some?) variables of AbstractCountry package protected, meaning the variables are only visible to classes within the package.

This has the effect of preventing countries accidentally changing variables when they shouldn't be, but still allowing the handlers to access the variables.

Speak now, or hold your peace.

**Comment by azyzio** [comment]
I looked into it yesterday (see #10). What is cool about package protected variables is that carbon reduction / absorption handlers won't be affected.

However e.g. Monitor will be affected and will require the creation of setters for the variables. At the end, not much is therefore changed as there would exist public getters and setters for most of the fields. Although it would be a better OO approach, it doesn't really prevent countries from accidentally changing the variables, so the goal would not be acheived.

**Comment by tumblerer** [comment]
Unless you move monitor into the same package.

Public getters arent a problem.

**Comment by azyzio** [comment]
Yeah, actually it is only a monitor that is using Abstract Country fields and is not in the package.

**Comment by tumblerer** [comment]
Actually, its TradeProtocol too.  Just to update you that's been moved into the countries package for the moment, for testing.  But only in group1 branch.

**Comment by tumblerer** [comment]
This has all been done now, but people need to add getters to their behaviours.  Will close and open with something new.
