### ISSUE TITLE
Group 3 branch is very far behind development

### ISSUE THREAD

**Issue by jjonnnyy** [farhanrahman/kyoto#41]
The group 3 branch is currently 187 commits behind development. Developing on a branch that is so far behind development will likely cause problems when you try to merge back in. 

Could you please sort this by merging development into group3 - be extra careful about what changes are introduced, it is likely you will need to manually resolve some conflicts.

**Comment by azyzio** [comment]
@georgePil: I am not sure if you know what you are doing now :D You just updated the development branch without applying the changes from your group 3 branch. You think should focus on this issue quite quickly.

**Comment by georgePil** [comment]
Done baby :p

**Comment by georgePil** [comment]
everything up to date on group3

**Comment by azyzio** [comment]
It doesn't look like that :D Check https://github.com/farhanrahman/kyoto/network to see if the merge went properly. There should be a line joining development with group2

**Comment by jjonnnyy** [comment]
Right, I think it's all fixed now. At some point group3 should merge their work into development.
