### ISSUE TITLE
Mongo DB connector for simulation output data

### ISSUE THREAD

**Issue by oliviervg1** [farhanrahman/kyoto#44]
Can @maxrev17 and @webbo89 come up with a list of data that they want to be able to represent?

Farhan can then implement a DataToMongoDB function which will be called at the end of every year/session in Abstract Country?

**Comment by webbo89** [comment]
This sounds ideal to me - i've written a provisional wiki on the KyotoUI page of what we'd find useful and tried my best to closely match the functionality of AbstractCountry.

https://github.com/kyotoprotocol/KyotoUI/wiki/SimulationOutput

Thoughts/Suggestions welcome of course!

**Comment by farhanrahman** [comment]
I realised that Presage provides API for individual agents to store their data. It will appear in agents collection in the mongodb i think. So the way to solve this would be to add functions in AbstractCountry that sets properties every tick or year i.e. dumps the countries data into mongo. These values will be the true values that countries have every tick. I think this should be added after the behaviour() function is called.

**Comment by oliviervg1** [comment]
Sounds good to me. Do you have time to do it Farhan ? Otherwise, I don't mind doing it.

**Comment by farhanrahman** [comment]
Hey Olivier...i don't think I can do it now as in I can do it in the evening/at night. I can finish it by today though..

**Comment by oliviervg1** [comment]
Ok: here is some initial stuff https://github.com/farhanrahman/kyoto/commit/adb59ebe4b52267bbb915dc4a5b88c4108c2791e

I don't have time tonight to continue, so could  you have a look at it Farhan? 

Thanks

**Comment by farhanrahman** [comment]
Awesome man!! Mbut i was thinking if we could keep a history of data i.e. maps getting updated and so when we store we just do setproperty("dave",blah map)..should be good...because currently only stuff will get overwritten so we will only have the last tick's data..

**Comment by farhanrahman** [comment]
Cheers man..i will finish it off...

**Comment by oliviervg1** [comment]
Damn I didn't know it overwrote the data every tick. That doesn't make a lot of sense to be honest...

**Comment by farhanrahman** [comment]
Added the dumping facility. However the onSimulationComplete() function is no longer called now. I am closing this issue as the functionality is there. Its just an issue with Presage i guess....
