### ISSUE TITLE
Balancing of input parameters

### ISSUE THREAD

**Issue by oliviervg1** [farhanrahman/kyoto#46]
Currently, most functions return unrealistic data.

We need to focus on balancing the input data as soon as possible!

Current work in [Balancing](https://github.com/farhanrahman/kyoto/wiki/Balancing)

**Comment by tumblerer** [comment]
Using this as a place to store ideas:

The first point of balancing is that we must achieve a drop of 5% year on year.  This gives us an idea of how much energy should change year on year, which is a pretty strong change to move forward from.  This directly means we can balance GDP changes.

**Comment by tumblerer** [comment]
Further to that, realistic data puts GDP spending as around 0.5%, optimistically, on Clean Energy drives.  Realistically, different countries dedicate a different amount to clean energy, generally far less.  However, since we can invest in industry also, this will do.

So we need to achieve a 0.5% drop per year with 0.5% of GDP.

**Comment by tumblerer** [comment]
Monitor Tax  / Monitoring Price = Number of Countries monitored. Kinda.  Need to find the average GDP of all countries to find the sanction rate.

**Comment by tumblerer** [comment]
Sanctioning needs to be proportionate to the risk of get caught while cheating and the cost needed to reduce carbon by the 0.5% needed

**Comment by tumblerer** [comment]
Carbon Reduction and Carbon absorption need to be a comparable cost ideally.  The amount to the reduce by should be roughly equal to a proportion of the given money and the energy drop needed per round.

**Comment by tumblerer** [comment]
Some calculations:
avg ALA : 15%
avg DI : 72%
avg Drop/y : 10685430
avg GDP : 158788
avg cash : 793.94

**Comment by tumblerer** [comment]
Avg ALA/CarbonOuput ~ 5500

**Comment by tumblerer** [comment]
2.6 tonnes of co2 per acre.

0.3846 acres per tonne.

0.0156 km^2 per tonne

http://www.treesintrust.com/environmental.shtm

**Comment by tumblerer** [comment]
For carbon Investment price.

The investment cost > the return for the next few years gained by increasing GDP.

**Comment by tumblerer** [comment]
Need to look at the cost to achieve an increase of energyOutput by a certain percentage

**Comment by tumblerer** [comment]
Going to call this done for the moment.  Not going to continue working on it unless I get some feedback
