### ISSUE TITLE
Adjusting behaviours to use getters.

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#49]
The country variables have now been changed to package protected.

This means to access variable values you'll need to use getters in your behaviour.

@georgePil ,  @whitebloodcell , @n1kunj

**Comment by n1kunj** [comment]
All fixed on my end, I'll push changes when my behaviour code is a little more done.

**Comment by georgePil** [comment]
Done and pushed! This makes it harder to cheat though, good plan :p

**Comment by tumblerer** [comment]
I'll assume Tom's done this. If not, he'll have pretty useless code.
