### ISSUE TITLE
Carbon Absorption (maybe Reduction) gives improvement for free

### ISSUE THREAD

**Issue by sc1109** [farhanrahman/kyoto#51]
Using these in TradeProtocol for a CDM, gives the investee the benefit to absorption/output without costing any money!!!

**Comment by piotroslaw** [comment]
Could you elaborate?

**Comment by ChrisSSocha** [comment]
Have done some ad-hoc testing and it appears to work fine. Sam, can we have your values for arableLandArea, landArea, carbonOutput, availableToSpend and carbonAbsorption to do some testing with please.

**Comment by sc1109** [comment]
I used the same testtrade2 simulation values Farhan chose. Are you not seeing both players start with ~460k money, Stuart going to ~560k, Farhan down to ~360k? Stuart then reports having gained some absorption/reduction and Farhan reports gaining offset, but Stuart is never deducted the 10k for creating that absorption/reduction.

**Comment by tumblerer** [comment]
Works as expected.
