### ISSUE TITLE
CDM failed action

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#53]
We were discussing the case of: what if a CDM transaction was approved, and money and credit had changed hands, but the handlers threw an error and the action was carried out.

Example:
A country wants investment to perform carbon reduction.  A trade is accepted at a certain cost price.  However, partway through the trade, the country spends the rest of its money on carbon reduction.  The money from the trade is no longer enough to pay for the agreed reduction, and error is thrown and the action is not performed.

Admittedly, this is unlikely and somewhat stupid behaviour from the country.  Further to that, if the money changed hands the country who was invested in would keep the money, and no real harm would have been done.  However, I thought this is worth putting out there as there could other such hypothetical situations.

**Comment by farhanrahman** [comment]
Man good spotting. I think I may have found a possible bug from your thoughts. Its quite difficult to write it here but I think we should discuss it tomorrow.

**Comment by tumblerer** [comment]
Fixed by Sam

**Comment by farhanrahman** [comment]
what was fixed by sam? can you specify? I have restructured the TradeProtocol completely not too sure which version you are referring to

**Comment by tumblerer** [comment]
Ok tested and agreed to be working by Sam

Fixed by Farhan.
