### ISSUE TITLE
Clean Development Mechanism Model

### ISSUE THREAD

**Issue by azyzio** [farhanrahman/kyoto#54]
I think that the model we are using for Clean Development Mechanism should be reconsidered.

Most of my knowledge about the current model is based on the Document "Clean Development Mechanism" in Google Docs, please let me know if any of it has changed.
1. When the nonAnnex country invests in reduction/absorption it should be the carbon  output / carbon absorption that are adjusted accordingly. In the current case it is carbon offset which does not make sense as these investments change the rate at which carbon is created, not the amount of extra credits that are gained by the country
2. The reward that the Annex country gets for investing in a nonAnnex should be either in changing the emission target (increasing it temporarily) or granting the carbon offset. The later is easier to implement to we should probably stick with this option. This then agrees with what is described in the document. The thing I would consider again is if the Annex country carbon offset gain should not be proportion of the change in carbon output(/absorption) of a nonAnnex country. I guess that if we had a constant that controls it, it would be easier to adjust the prices properly.

If this is how the mechanism is actually implemented then post it here, I will update the document accordingly and close the issue.

**Comment by sc1109** [comment]
It currently works like this:

NonAnnex receives money which it immediately invests in Absorption or Reduction of the same amount of Carbon as is granted as Offset to the Annex country.

Whether the carbon absorption or output should map one to one to offset, is up to you.

**Comment by tumblerer** [comment]
The docs have become fairly outdated.  A weeks a long time in this project it seems.  Sam's right on.

**Comment by georgePil** [comment]
@sc1109  "NonAnnex receives money which it immediately invests in Absorption or Reduction of the same amount of Carbon as is granted as Offset to the Annex country". 

This has to be done by the countries behaviour though it does not happen immediately by the protocol right? Also to use it is it by just using the functions in AbstractCountry?
protected final void broadcastSellOffer(int quantity, double unitCost)
protected final void broadcastBuyOffer(int quantity, double unitCost)
protected final void broadcastInvesteeOffer(int quantity, double unitCost, InvestmentType itype)  ?

**Comment by sc1109** [comment]
Yes, stuff happens eventually after a couple turns (i.e. the seller may actually receive money before the buyer loses any).
Those are the right functions, remember to make sure quantity and unit cost match for investment before you throw them into an offer using something like:

unitCost = this.carbonAbsorptionHandler.getInvestmentRequired(quantity)/quantity;

otherwise you'll see a bunch of exceptions

**Comment by georgePil** [comment]
Thanks man! From this, shouldnt the quantity's type be double since carbonOutput, carbonOffset are double?

**Comment by georgePil** [comment]
Or maybe I misunderstood something :p

**Comment by sc1109** [comment]
update:

just call broadcastInvesteeOffer(quantity, InvestmentType);

that is all
