### ISSUE TITLE
Development branch will not run

### ISSUE THREAD

**Issue by cmd08** [farhanrahman/kyoto#56]
Attempting to run development branch d067ce16903f16b761d385cee7ab83e2f720ce2a causes an error:

> java.lang.InternalError: Got MethodID of ReferenceType that is not a member of the ReferenceType occurred retrieving stack frames. Got MethodID of ReferenceType that is not a member of the ReferenceType

**Comment by cmd08** [comment]
This then forces eclipse to quit. Fun!

**Comment by Sergeus** [comment]
Fixed this
