### ISSUE TITLE
Dynamically load GameConst values

### ISSUE THREAD

**Issue by webbo89** [farhanrahman/kyoto#59]
For the attention of anyone else who would like to pass dynamic parameters through presage for the simulation! 

But mostly for @Sergeus  - I've used all but one of the constants (TICKS_IN_YEAR) in GameConst to be initialised:

They have been added to the CSV and can be added in a similar method to LPG game. Parameter declarations use the naming convention that GameConst uses! Feel free to drop any you think we have added unnecessarily. 

```
    @Parameter(name = "GROWTH_MARKET_STATE")
public int cCount;

See for params: 
```

Related link on how we load params if anyone is interested: https://github.com/kyotoprotocol/KyotoUI/wiki/ImportExport

**Comment by webbo89** [comment]
PARAM CSV https://github.com/kyotoprotocol/KyotoUI/blob/master/admin/csv/defaultdataparams.csv

**Comment by Sergeus** [comment]
I'm working on this now, it's slightly more complicated than I first expected.

**Comment by Sergeus** [comment]
This works now.   It's commented out for now, so that we can run other simulations without giving all of those values.
