### ISSUE TITLE
Single Agent, Kyoto Annex 1

### ISSUE THREAD

**Issue by cmd08** [farhanrahman/kyoto#6]
Single Agent attempts to reduce carbon output.

**Comment by Sergeus** [comment]
I was working on this today, made quite a bit of progress.   Should be able to finish it on monday.   (Assuming Canada starts in annex1?   Regardless, that's the behavior I'm implementing anyway.)

**Comment by Sergeus** [comment]
I have a working simulation that almost does this, but the carbon reduction handler outputs numbers way out of the proper range.   This issue has been superseded by Piotr's work on the carbon reduction formulae.
