### ISSUE TITLE
investInCarbonAbsorption

### ISSUE THREAD

**Issue by farhanrahman** [farhanrahman/kyoto#63]
What is the deal with this function throwing a NotEnoughCarbonOutput exception when it doesn't throw it in the function?

**Comment by n1kunj** [comment]
That may have been my fault - I cleaned up some of the code in the absorption handler, including a function where an exception was thrown, caught within the same function and then rethrown.

I assume this function is called in investInCarbonAbsorption (which I never bothered cleaning), which still throws an exception that the inner function never throws. It's perfectly safe to just remove that useless throws declaration.
