### ISSUE TITLE
QueryEmissionsTargetHandler.java Compile Error

### ISSUE THREAD

**Issue by cmd08** [farhanrahman/kyoto#64]
In e994b80ac3691a8e1508bb985934460973cbbee8, line 46 has a compile error: requires an additional argument (year of target). Should this be inferred from the time service?

**Comment by n1kunj** [comment]
Can we make this have an overloaded operator? If you call the function without the year it infers the year from the time service, else if you call it with a year x it works out the target in now + x years, assuming we meet all previous targets? It would make my life writing behaviours so much easier.

**Comment by jjonnnyy** [comment]
@n1kunj Firstly, agents can not access functions from services. Secondly, it is easy to predict your yearly targets to the end of the session however beyond that it would be quite unreliable. As a rough estimate, targets are simply a reduction between session targets of 5% spread linearly over the years in the session.
