### ISSUE TITLE
Starting a Simulation from MongoDB

### ISSUE THREAD

**Issue by webbo89** [farhanrahman/kyoto#68]
Currently I understand the sim can be run via debugging the project, however we're looking for the simulation to be called via an ID and load the necessary mongo files.

@maxrev17  and myself are prepared to make changes to ensure the data goes in correctly, i.e. by sorting types ETC.

However with @farhanrahman  the current stumbling block appears to be with mongo + the kyoto sim.

I've tested the simulation by creating the necessary records through the Presage CLI (so the simulation could be started entirely without KyotoUI)  and I still get the error. So while i think KyotoUI will have bugs, it currently appears that the trouble is with presage + kyoto + mongodb!

**Comment by cmd08** [comment]
Have you looked at the other Run files? (https://github.com/Presage/Presage2/wiki/Storing-simulation-data onwards in the Presage2 tutorial).

Could you make a really simple Presage project (perhaps just fork an existing working one from sammacbeth?) to test on for now?

**Comment by webbo89** [comment]
Thanks! That's currently the best option, kyoto is pretty big to be poking around for the error!

**Comment by cmd08** [comment]
Ok, take a look at e2968745cfe44321c4465c43e79fcd39852f71b4. You should now be able to start a simulation using this simulation class:  https://github.com/farhanrahman/kyoto/blob/development/kyoto/src/main/java/uk/ac/ic/kyoto/simulations/NoKyoto.java

The instruction goes something like `uk.ac.ic.kyoto.simulations.NoKyoto countries=x finishTime=y`

**Comment by piotroslaw** [comment]
seems resolved, closing
