### ISSUE TITLE
GDP Rate never falls below 1

### ISSUE THREAD

**Issue by Sergeus** [farhanrahman/kyoto#69]
As it is now, GDP rate never falls below 1, so countries' GDP can never drop.   I understand recessions in the real world do not immediately correlate with falling GDP, it's falling GD growth rate.   However, our simulation won't work if GDP doesn't ever fall.   If you slash industry to reduce your carbon output, your GDP will only, at worst, stay the same, so you'll keep getting the same amount of money.

**Comment by tumblerer** [comment]
More accurately:

Currently GDP growth does not become negative unless growth is so small and the world is in recession.

Will reformulate now.
