### ISSUE TITLE
Multiple Simulation Files

### ISSUE THREAD

**Issue by cmd08** [farhanrahman/kyoto#74]
Hi there,

You'll notice that Simulation.java has moved to the simulations package. As we're all testing different things, we need different Simulation files. I something like "RealKyoto.java" will be the one which pulls in the data from the csv and models Kyoto. For now there's Simulation, and NoKyoto. Please feel free to add your own there!

**Comment by Sergeus** [comment]
I'm correct in thinking that when someone wants to run a simulation, they need to adjust their arguments in the debug/run configurations to point to the correct simulation file?

**Comment by cmd08** [comment]
Yup! You go Run>Run/Debug Configurations...>Arguments tab and change the first argument to the fully qualified class name. 

For instance: `uk.ac.ic.kyoto.simulations.NoKyoto countries=10 finishTime=10`

**Comment by cmd08** [comment]
Think everyone's seen this now... Closing
