### ISSUE TITLE
Energy and CO2 emissions stay constant even if GDP increases

### ISSUE THREAD

**Issue by cmd08** [farhanrahman/kyoto#75]
If you let a country exist on its own without Kyoto, monitoring etc. its GDP will increase, but energy output and CO2 output stay the same. I think this is wrong - increased GDP implies industry growth, and so energy output and CO2 should increase too.

Thoughts?

**Comment by n1kunj** [comment]
Does it really matter? The increase is pretty much uniform across all countries, so we could just count it as global inflation. Market prices/cost of reduction etc. are increasing as well, so with some proper balancing it should all mostly cancel out.

**Comment by cmd08** [comment]
If all things are equal for all countries, should GDP not increase either? 

I think the trend prior to Kyoto was that for countries who's GDP increased more, their CO2 emissions increased more too. 

I think it might be worth trying to model reality a little closer on this as it's not a particularly tricky issue, and it also shows quite nicely what would've happend without kyoto.

**Comment by tumblerer** [comment]
I'm rewriting the GDP Growth rate function.  This has been fixed, but not yet completed or pushed.
