### ISSUE TITLE
joinKyoto() & leaveKyoto() slightly misleading

### ISSUE THREAD

**Issue by cmd08** [farhanrahman/kyoto#76]
These should either throw an exception, or be renamed to show that they aren't guaranteed (something like tryToJoinKyoto() etc.)

I think throwing an exception is probably best.

**Comment by jjonnnyy** [comment]
Why would an agent not be able to join/leave kyoto?

**Comment by cmd08** [comment]
There's a time limit you have to wait to rejoin if you leave. @Sergeus @tumblerer can you help?

**Comment by tumblerer** [comment]
You are correct.  It's to prevent countries abusing the leave function in order to reset sanctions etc.  An exception should be thrown for the countries.

**Comment by cmd08** [comment]
Will add the exception now, rather than having them return true/false
