### ISSUE TITLE
Non-Annex-One Package

### ISSUE THREAD

**Issue by Sergeus** [farhanrahman/kyoto#79]
The file BIC.java doesn't compile.   As far as I can see, it's using an outdated version of the investeeOffer function, giving the wrong arguments.

**Comment by georgePil** [comment]
Yeap the only problem is the inveesteoffer for the CDM protocol. where instead of giving int for the quantity I give double. In my version quantity of inveesteOffer is int and I am in the development. Is yours double?

**Comment by georgePil** [comment]
Also here : https://github.com/farhanrahman/kyoto/wiki/Carbon-Development-Mechanisms 

It is int. But i think it should be double since carbonOutput is double.

**Comment by Sergeus** [comment]
You're right, that should be a double, not an int.   I've changed Offer, hopefully that doesn't break anything.   @farhanrahman or @sc1109, was there a reason for that being an int?

**Comment by farhanrahman** [comment]
Hey thanks for changing that..Offer class was made a long time ago so we didn't change it while the constructors were changing so much because of changes to data types.
