### ISSUE TITLE
Change to AbstractCountry which makes trading initialization easier

### ISSUE THREAD

**Issue by Sergeus** [farhanrahman/kyoto#80]
I've just moved the initialization of the tradeProtocol field up to AbstractCountry so that each individual country doesn't have to deal with the overriding function constructor complicated-death-thing in their initialize function.   However, everyone now needs to implement the acceptTrade() abstract function.   This returns a boolean, and it should be used to outline the conditions with which your country will accept a trade.   You still have a chance to negotiate in processInput, this just makes your initialization code simpler.   

A very simple example of an implementation of acceptTrade() would be to return true all the time, which would accept all trades that get that far in the state machine.   I'll be updating the trade protocol quickstart page so it's correct with all of the recent changes.   (acceptTrade() has two arguments, you can use them to work out who the trade is from and all of the information about the trade itself.   Eclipse will point out what fields you can access from them.)

**Comment by farhanrahman** [comment]
Thats a good one. I was thinking we should move the responding function from processInput to abstract country. I realised the process input function gets all the messages and it is quite easy to send the offer that is already in the conversation into a new conversation. What that does is makes the country go into a never ending cycle of offering the same offer. That causes the TradeProtocol to warn that "trade has already happened"

**Comment by Sergeus** [comment]
Ok, that is an evil problem.   But how can we solve it?   If we pull processInput up into AbstractCountry how do the individual countries actually implement logic without this issue occurring?   We need to pass the input message down the hierarchy to them, but it exposes us to the same issue either way.

**Comment by farhanrahman** [comment]
we don't pull processInput to abstract country. We basically move the ability of countries to start an offer to the AbstractCountry. However i just though of an easier fix. In the offer function I can check whether the offer message is of type TradeProtocol. If thats the case then I don't start the conversation. If the offerMessage type is BROADCAST then i allow the agent to start the conversation... I think it will work. I'll add that check...

**Comment by Sergeus** [comment]
Argh, I should have updated here when I started working.   I'm moving processInput up to AbstractCountry and adding two abstract methods that countries have to implement.   One, respondToOffer(), which lets you look at an offer and see if you like it, and then sendOfferResponse() (name may still change) which lets people do the negotiation stuff, the offering to buy fewer tons than the other guy is selling and stuff.

**Comment by Sergeus** [comment]
I'm now considering a single function that returns null if you don't like the offer, otherwise this gets potentially very confusing for the countries.

**Comment by georgePil** [comment]
It is confusing! :p

**Comment by Sergeus** [comment]
That's because it's not finished yet. :P   It works, but the way it's set up now requires countries to write a lot of tradeProtocol-related code in their own implementations.   I'm trying to reduce the amount they have to do, so accepting an offer is similarly as simple as sending one.   (Sending an offer in the first place is great, you just call a function and you're done.)

I've run into a problem with my attempted solution, because countries' implementations can't create new offer objects to return to AbstractCountry, because of the previous fix to prevent people messing with tradeProtocol.

@farhanrahman, does your solution mean that countries don't have to write that terrifying processInput overload thing?

**Comment by Sergeus** [comment]
I've removed my changes. my solution didn't work.   I'm gonna try to find another way to do this.

**Comment by farhanrahman** [comment]
Hey stuart..I think removing processInput to AbstractCountry isn't a good idea. This is because processInput is a very crucial part of communication. If we want to extend the functionality by adding some other types of communication then it would be impossible for people to override processInput and add their own behaviour. Lets leave it so that people in the future can use this to make their own countries and add their own protocols...Just leave processInput where it is. I will write a method in trade protocol that simplifies this whole thing.

**Comment by Sergeus** [comment]
Cool, if you're fixing it that's fine.   Soon would be good though so I can finish the documentation and everyone can do their final country implementation as soon as possible.
