### ISSUE TITLE
Emissions Target not Changing

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#83]
I've run a 10 year simulation on development, and the emissions target isn't changing.

That's bad.

**Comment by farhanrahman** [comment]
Its not good everything is falling apart!!'

**Comment by tumblerer** [comment]
It get's worse, I tried to run it for 20 years and it crashes out.  But emission targets still don't change.

**Comment by jjonnnyy** [comment]
I apologise for writing shitty code, I'll see if I can track the bug down now.
