### ISSUE TITLE
Country Constructors Should Initialize Kyoto Membership Level

### ISSUE THREAD

**Issue by Sergeus** [farhanrahman/kyoto#87]
Being a member of the Kyoto protocol is no longer a binary status, with reference to your membership field.   Now, you have a field called kyotoMemberLevel which says whether you are annex one, non annex one, or a rogue state.   If you are NOT annex one, you must initialize this variable to the correct value using the function setKyotoMemberLevel().   This function will only be accessible for the first turn of the game, so make sure you initialize it in your constructor.

You need to give setKyotoMemberLevel() an argument, which is the type you want your country to be.   There are three available values:

KyotoMember.ANNEXONE
KyotoMember.NONANNEXONE
KyotoMember.ROGUE

**Comment by tumblerer** [comment]
@whitebloodcell , @piotroslaw , @georgePil

**Comment by georgePil** [comment]
Done ;p
