### ISSUE TITLE
Current Abstract Country is too narrow

### ISSUE THREAD

**Issue by azyzio** [farhanrahman/kyoto#9]
In the current implementation of Abstract Country, we include functions that are used for reporting, monitoring taxations etc. However, not all the countries (e.g. NonAnnexOne), need this functionality.

I suggest moving the Kyoto specific functionality to a separate class that extends from Abstract Country.

Do you agree and is there anyone that volunteers for doing it?

**Comment by webbo89** [comment]
This is a good point - 

From the initialisation side of things - we've been anticipating this too. But rather than adding classes we thought that you may want to expand your agent constructor and we don't think it would be hard to do, so using AbstractCountry as a minimum you could use your own agent to add more fields.

Then on construction time I imagine it would look something like this:

```
new EUAgent(id,"France", etc, target, eu_political_will); 
new NonAnnex(id,"Bangladesh", etc, farhan_superpower); 
new USAgent(id,"USA", etc, political_start_party); 
```

Perhaps as you say, modfiy A.C. so EU has a target, the others aren't required.

**Comment by azyzio** [comment]
Annex 1 sustain countries (e.g. Russia) also need all the functionality needed for kyoto and they have different behaviour than EU countries.
I think adding a new class that extends from Abstract Country and implements kyoto-related functionality would make sense. Having it:
- EU inherits from AbstractKyotoCountry
- Sustain inherits from AbstractKyotoCountry
- NonAnnex inherits from AbstractCountry
- US inherits from AbstractCountry

**Comment by azyzio** [comment]
And I agree that each type of a country type can introduce their own parameters if they wish to, but this is not what I was concerned about here.

**Comment by azyzio** [comment]
As there in no one against this change and I consider it quite an important one, I will work on it

**Comment by Sergeus** [comment]
Sorry, I sorta need to oppose this change.   If countries that are part of/not part of Kyoto inherit from different classes, then countries can't join or leave the protocol.   (Which is the defined case for Canada.)

**Comment by azyzio** [comment]
I can see that Tom has come up with a different solution to this problem, can you explain what?

**Comment by Sergeus** [comment]
Basically, as far as I know, the AbstractCountry has a field that says whether or not the country is a member of Kyoto.   The Kyoto-only stuff like monitor tax just checks that the country is a member before executing.

**Comment by azyzio** [comment]
nice and simple.
Ok, if all the countries may be kyoto then I don't consider it an issue anymore.
