### ISSUE TITLE
Reason to leave Kyoto

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#92]
Annex1 countries shouldn't be leaving kyoto, but if they get stuck in recession for multiple years (~6 perhaps), leaving kyoto is the only sensible option.

Countries should leave until their countries economy has recovered, and then rejoin kyoto.

**Comment by cmd08** [comment]
Lets leave this up to individual countries for now, bearing in mind that they CANNOT rejoin in the first version
