### ISSUE TITLE
Test: Joining and leaving Kyoto

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#93]
Need to test how leaving and joining kyoto behaves.

Particularly with reference to how emission targets and maintained and recalculated.

**Comment by sc1109** [comment]
Rejoining is very difficult due to the number of lists you need to be added to at the right time. Me and Tory think we should forbid rejoining for now, is this devastating to anyone?

**Comment by cmd08** [comment]
Fine, rejoining is in the next build.
