### ISSUE TITLE
Public cheaters map from monitor

### ISSUE THREAD

**Issue by ChrisSSocha** [farhanrahman/kyoto#94]
Feature to be added if we have time. Monitor should add a getCheaters(...) which returns a copy of the map to participates that request it (Suggest to make a copy of the Map, and return an Iterator)

**Comment by cmd08** [comment]
How about an ImmutableMap? http://google-collections.googlecode.com/svn/trunk/javadoc/com/google/common/collect/ImmutableMap.html

Then you can do `getCheaters().containsKey("Country")` to see if a specific country is a cheat without having to iterate over the whole map explicitly.

**Comment by ChrisSSocha** [comment]
Perhaps `Collections.unmodifiableMap(/*map of cheaters*/)` ??
